### PR TITLE
Add facebook-cli

### PR DESCRIPTION
**Pull request by specious**
Added [facebook-cli](https://github.com/specious/facebook-cli), a command line interface to Facebook.

Here's an asciicast:

<a href="https://asciinema.org/a/87129"></a>

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for your suggestion. However, due to my disdain for all things Facebook burning with the white-hot passion of ten thousand suns, I'm not going to add it to the list. I believe you will have no problem finding an audience among the 1.6 billion users though.

**Comment by specious** [comment]
You might enjoy the part about the [limitations](https://github.com/specious/facebook-cli/tree/093705df0587d502d2dc1ceba574923f01c791a0#why-cant-i) of the Facebook API :feelsgood:

**Comment by herrbischoff** [comment]
No real enjoyment but also no surprises there. Facebook is toxic to [the open web](https://qz.com/545048/death-by-a-thousand-likes-how-facebook-and-twitter-are-killing-the-open-web/), news reporting, diversity of opinion, [privacy](https://www.youtube.com/watch?v=5pFX2P7JLwA) in general and even [its users' health](http://www.forbes.com/sites/alicegwalton/2015/04/08/new-study-links-facebook-to-depression-but-now-we-actually-understand-why/). And they want to keep you inside their premises at all costs.

**Comment by specious** [comment]
Use `facebook-cli` to study how Facebook works.

**Comment by specious** [comment]
Valid points.

**Pull request closed without merging**
