### PR TITLE
Add undecided.js to Miscellaneous List

### PR DESCRIPTION
**Pull request by marcelmouse**

### CODE REVIEW

**Comment by herrbischoff** [comment]
This is one of the most useless things I have ever seen.

**Comment by marcelmouse** [comment]
@herrbischoff you didn't even try it!

**Comment by herrbischoff** [comment]
If it does what it says on the label, it's not awesome. If it does something else, it's misleading. If it's an art project, humorous, clever or whatever, it's misplaced. Either way, it does not belong here.

And I can read source code:

```javascript
say.speak('fuck!', 'Alex', .8);
```

Please take a moment to reflect on the possibility that not everyone shares your particular take on what you consider to be funny or artsy.

**Comment by herrbischoff** [comment]
Very mature, sending your buddies along to "thumb down". I'm going to lock this. This isn't Facebook.

**Pull request closed without merging**
