### PR TITLE
Added CFT to Automation section

### PR DESCRIPTION
**Pull request by rfo909**
[CFT](https://github.com/rfo909/CFT) is an interpreted functional programming language, and an interactive command line program, for automation.

### CODE REVIEW

**Comment by abitrolly** [comment]
The description says it is a config tool. Could you give an example of changing YAML config? Like some config for Kubernetes. Also, the role of `P(1,Dir)` function is unclear.

**Comment by rfo909** [comment]
The role of the P(1,Dir) expression, is to grab parameter 1, or if missing or null, run default expression "Dir", which is a global function. When called without arguments, it returns current directory (a Dir object). If a parameter 1 was given, the default expr ("Dir") is not executed.

Regarding creating a YAML file, here is an example from the ServersMaintenance script under code.examples, where we build the netplan configuration file, using a "here" document and some merge codes for ip and nic. 

```
PDict("ip","nic").mergeCodes =>data
<<< EOF
network:
  version: 2
  renderer: networkd
  ethernets:
    ${nic}:
      dhcp4: no
      gateway4: 10.0.0.138
      addresses: [${ip}]
      nameservers:
        addresses: [10.0.0.3, 10.0.0.4]
>>> EOF
->line
    out(line.merge(data))
/VMNetplan
```

The call to PDict("ip","nic") is short for
```
Dict
   .set("ip",P(1))
   .set("nic",P(2))
```

The Dict() global function creates an empty dictionary.
The Dict.mergeCodes() function creates new dictionary where keys are renamed from "key" to "${key}".

**Comment by abitrolly** [comment]
@rfo909 so the `P` is about command line parameter, or which parameter is it?

The YAML example you've shown produces a new YAML config from template. I am right that CFT is unable to modify existing YAML config changing only certain keys leaving all others untouched?

**Comment by rfo909** [comment]
No, it is parameters to the function, which is defined following the code, using "/" + ident.

Example script, let's call it Test
```
# Test function
# --
   P(1,4)=>a
   P(2,3)=>b
   a+b
/f
```
Then in interactive mode:
```
$ :load Test
$ f(1,2)
  3
$ f   # no params
  7
$ f(1)
  4
```

I will clarify a bit in the Readme.md I think :-) Thanks for your interest!

**Comment by rfo909** [comment]
I've clarified in the Readme.md file now :-)

**Comment by rfo909** [comment]
To modify existing YAML, other than textual replacement, would require a YAML parser, which CFT does not have yet, partially becase I have not needed it, but also because YAML is a bit of a complex format. Now, for JSON on the other hand, I have created a parser/generator, though rudimentary still, as it does not preserve order of fields at same level, which if not technically required, would look more tidy. That is on the TODO list at least :-)

**Comment by abitrolly** [comment]
I don't see much difference between this tool and plain Ruby then. With the exception that the latter has much more different libs and parsers for automation and configuration tasks.

**Comment by rfo909** [comment]
Just a small comment: the name ConfigTool doesn't limit the scope to configuring. I'm mostly using it to collect and traverse logs, start and stop services (via PowerShell at work), deploy configuration files for elastic search / filebeat etc, and searching source code. At home I use it to automate cloning and initialization of VM's with KVM. 

It is also nice for creating configuration files to be deployed to ElasticSearch clusters, with Filebeat instances pointing at Logstash pipelines, which in turn point at ElasticSearch nodes. 

Also using it to check out stuff from git, move it around, then create Docker images, which in turn can be run in different ways, mounting up bind volumes for logging, configuration etc.

And it is a nice calculator :-)

**Pull request closed without merging**
