### PR TITLE
adding dotdrop to the list

### PR DESCRIPTION
**Pull request by deadc0de6**
This PR adds dotdrop to the list of CLI apps, thanks !

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for the submission. I use Homeshick because it has no dependencies apart from Bash or csh (a given on most platforms). I don't like having to install Python and several modules on a host just to be able to share configuration files.

Is there some functionality your solution offers that has a substantial benefit compared to Homeshick?

**Comment by deadc0de6** [comment]
It's difficult to answer since I haven't used homeshick however the following features from dotdrop are, from what I've read, not available in homeshick. Please correct me if I'm wrong:

* ability to template your dotfiles (consider `.xinitrc` when your home desktop is running awesomeWM and your office laptop is running bspwm): with dotdrop you have a single file stored, no duplicate and an easy deployment solution
* ability to create profiles that have different combinations of dotfiles, for example a profile for your cloud servers that have only a subset of all dotfiles you store in dotdrop

**Comment by herrbischoff** [comment]
This indeed sounds interesting. So, if I understand correctly, I could template a `init.vim` file that contains different settings for different environments, say, a minimal one for servers and a full-blown one for desktops? How would that even work easily without interfering the usual editing process?

**Comment by deadc0de6** [comment]
I don't use neovim but yes, you could create a template that would generate different versions of the same dotfile on different profiles (a minimal one and full-blown one for example).

I'm not sure to understand your second question about the editing process but dotdrop is thought to be sync'ed through git so if you update on one host your dotfile(s) and commit/push them, you would then pull on the other side and simple run a `dotdrop.sh compare` (optional) to see how that would change the local files and then install them with `dotdrop.sh install`. Does that answer your questions ?

**Comment by deadc0de6** [comment]
check the blogpost ([https://deadc0de.re/articles/dotfiles.html](https://deadc0de.re/articles/dotfiles.html)) that might answer some of your questions

**Comment by herrbischoff** [comment]
Thanks for the link and taking the time to respond. It lead me to take a closer look at https://github.com/deadc0de6/dotdrop#example, which answers my question. So it is indeed possible to create a single configuration file and have parts of it generated or omitted based on the profile I select. I have not come across another tool capable of doing this. Very nice! I believe this warrants the label "awesome". :)

Just one suggestion: I wish it wasn't GPL-licensed but rather completely free (BSD, MIT, etc.) as GPL licenses are kind of a mess (clearly that's an opinion, not necessarily a fact).

**Comment by deadc0de6** [comment]
Thanks :smile:, happy you like it !

**Comment by herrbischoff** [comment]
Also, I recently found a nice lightweight solution for bootstrapping Python: https://github.com/pyenv/pyenv

**Comment by deadc0de6** [comment]
nice thanks for the pointer !!

**Pull request merged**
