### PR TITLE
Add nnn

### PR DESCRIPTION
**Pull request by jarun**
nnn is a terminal based file browser. It brings excellent desktop integration to the terminal with easy navigation, a disk usage analyzer mode, comprehensive file details and much more.

Features

- Super-easy navigation with roll-over at edges
- Jump HOME or back to the last visited directory (as you normally do!)
- Desktop opener integration to handle mime types
- Customizable bash script nlay to handle known file types
- Disk usage analyzer mode
- Basic and detail views
- Show stat and file information
- Show media information (needs mediainfo)
- Sort by modification time, size
- Sort numeric names in numeric order (1, 2, ... 10, 11, ...)
- Search directory contents using regex expressions
- Spawn a shell in the current directory
- Invoke file path copier (*easy* shell integration)
- Quit and change directory (*easy* shell integration)
- Open any file in EDITOR (fallback vi) or PAGER (fallback less)
- VIM-ish keybinds
- UTF-8 support

### CODE REVIEW

**Comment by jarun** [comment]
Note: the build break isn't introduced by this PR.

**Comment by herrbischoff** [comment]
What exactly is the upside of using `nnn` compared to `vifm`? Please elaborate.

**Comment by jarun** [comment]
I have updated the comment with the current list of features.

To begin with, nnn is insanely faster and memory efficient than other popular terminal file managers and disk usage analyzers ([comparison](https://github.com/jarun/nnn#performance)), thanks to C and highly optimized algorithms. I see vifm is in ruby. I don't think ruby would even stand a chance in this respect.

Next comes desktop integration. nnn implements [diverse strategies](https://github.com/jarun/nnn#file-handling) to handle files.

Also, I don't see a disk usage analyzer mode in vifm.

The last release of vifm happened in July 16, 2016. nnn is under active development and we are adding new features almost everyday now.

**Comment by herrbischoff** [comment]
Are we talking about the same `vifm`? https://sourceforge.net/p/vifm/code/ci/master/tree/

It's an established tool, regularly updated, written in C and very fast and light and highly configurable.

**Comment by jarun** [comment]
No, `sudo apt install vifm` picks up some ruby stuff.

I don't see a du mode in vifm.

**Pull request closed without merging**
