### PR TITLE
added nnn file manager

### PR DESCRIPTION
**Pull request by mutable-dan**

### CODE REVIEW

**Comment by mutable-dan** [comment]
ref: https://github.com/herrbischoff/awesome-command-line-apps/pull/28

the question was asked, why is it different from  a, b or c
https://github.com/herrbischoff/awesome-command-line-apps/pull/28#issuecomment-296473888

i don't think it matters how nnn compares to others such as vifm (though i think it's better and easier to use),  it's a choice the same way including ranger is a choice.
@jarun

**Comment by herrbischoff** [comment]
Well, if @jarun hadn't closed the pull request it might have been added back then. Look at the conversation, he's basically claiming that `vifm` is outdated and on the slightest bit of pushback, he closed the pull request. In my opinion, your reasoning is understandable but flawed. This list should be restricted to excellent tools, not everything under the sun. If you argue "choice", it's a catch-all thought-terminating cliché. If you truly want all possible choices, you get chaos. By that logic, this list should include everything anyone found useful, ever. Otherwise, you'd restrict choice. To keep things sane, the buck has to stop somewhere, and in case of this list that one is me. That's why I probe and ask questions.

Anyway, I will consider adding it since an unrelated party has suggested it again.

**Comment by mutable-dan** [comment]
understandable that you don't want everything.  i use nnn everyday, that's why I suggested it.  I prefer it over ranger, which is a fine project.  I have used vifm, but found the navigation in nnn easier.
I do think adding nnn would be a benefit to other people.

thanks

**Comment by jarun** [comment]
@herrbischoff 

>> The last release of vifm happened in July 16, 2016.

> he's basically claiming that vifm is outdated

That's a fact and that's a statement. The conclusion _outdated_ is yours, not mine. My statement says it was not frequently seeing new releases at that time.

The [comment](https://github.com/herrbischoff/awesome-command-line-apps/pull/28#issuecomment-296478290) is from Apr 24, 2017. The last release of vifm at the time was [v0.8.2](https://github.com/vifm/vifm/releases/tag/v0.8.2), released on Jul 16, 2016. And the 8 vifm releases from 5 Jun 2017 to 29 Jul 2019 (4 releases per year approx) establish pretty well there were scopes for improvement at the time of the comment.

> By that logic, this list should include everything anyone found useful

nnn is quite established in terms of availability, popularity as well as number of features. But this quote is an argument. The true reason is the following quote:

> the buck has to stop somewhere, in case of this list that one is me. That's why I probe and ask questions.

You are quite right there. The list literally is _ herrbischoff's awesome-command-line-apps_. However, this is a repo open to public contribution and this statement is missing from the [contribution guideline](https://github.com/herrbischoff/awesome-command-line-apps/blob/master/contributing.md). Please add it there. Probably something like _based on my personal preference_. In its current form it is generic, states the obvious and completely missing the _personal_ factor. And this is a serious suggestion, not a joke or sarcasm. If you think it's not reasonable, I can take it up with GitHub to understand contribution criteria and how to alleviate these conflicts better. I am forking your repo so I have a copy of the current contribution guideline which I can cite in case the need arises.

**Comment by herrbischoff** [comment]
I have no desire to continue discussing it in this manner. It's interesting to see how my initial instinct about your actions appears to have been quite correct after all.

**Pull request closed without merging**
