### PR TITLE
add vis text editor

### PR DESCRIPTION
**Pull request by erf**

### CODE REVIEW

**Comment by herrbischoff** [comment]
Please provide more information as to why you think it is awesome and where exactly its strengths are compared to Vim. The GitHub page gives off a vibe close to "coding a Vim clone just to not use Vim". I can see no advantages to, say, Neovim but many drawbacks.

**Comment by erf** [comment]
The main advantages as i see it is :
- It has a small c core without all the vim/neovim legacy crap, which makes it easier to build on
- It supports multiple cursors and sam structural regular expressions based command language
- It supports very large files
- You can extend it using Lua

**Comment by herrbischoff** [comment]
Thanks for the points. I'm going to check it out as soon as I get the chance and will review its merits. Regarding your arguments:

> It has a small c core without all the vim/neovim legacy crap, which makes it easier to build on

Sure, like all new software projects. But on the other hand it also lacks the massive community support to extend the editor with useful functionality that vis currently lacks.

> It supports multiple cursors and sam structural regular expressions based command language

That's more of a flavor and preference to me than a real feature. Multiple cursors are easily added in Vim, I use them all the time.

> It supports very large files

This could be a real win. Vim is notoriously choppy with medium to very large files.

> You can extend it using Lua

Same with Neovim.

**Comment by erf** [comment]
> Sure, like all new software projects. But on the other hand it also lacks the massive community support to extend the editor with useful functionality that vis currently lacks.

The author makes a point out of keeping the core small and avoid bloat. All the features i need is already there ( but i never used may plugins for vim ).

> That's more of a flavor and preference to me than a real feature. Multiple cursors are easily added in Vim, I use them all the time.

Multiple cursors as a core feature combined with SAM's regular expressions is very powerful, and not like anything supported in vim.

**Comment by herrbischoff** [comment]
I have checked out vis. It shows a lot of promise but in my opinion it is not quite ready for prime time yet. I will happily revisit once a truly stable version is released.

**Comment by erf** [comment]
No problem. Please feel free to elaborate on what you think it's lacking / why it's not stable for prime time. Maybe such feedback could help contribute to the project.
Btw. the author of vis added a [FAQ](https://github.com/martanne/vis/wiki/FAQ).

**Comment by herrbischoff** [comment]
The FAQ is really nice, thanks! I'll be keeping an eye on the development. A faster Vim-style editor with less cruft sounds like a worthwhile goal.

**Comment by herrbischoff** [comment]
Having revisited Vis, I feel it's worthwhile to include it in the list. The development seems to have slowed down a bit in recent months, but this is possibly due to the summertime. So, I'm going to merge this.

**Pull request merged**
