### PR TITLE
Add zoxide under Terminal

### PR DESCRIPTION
**Pull request by ajeetdsouza**
[zoxide](https://github.com/ajeetdsouza/zoxide) is a fast filesystem navigation utility written in Rust.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks. Please quickly explain what the difference to https://github.com/rupa/z is, except that this is written in Rust. Installation requires Rust to be present, which I would consider a downside. Also, `install.sh` requires Bash, which may not be present in non-Linux systems like FreeBSD or macOS.

**Comment by ajeetdsouza** [comment]
While zoxide is inspired by rupa/z, it builds upon it in the following ways:
1. It is one binary which supports every popular shell: bash, fish, PowerShell, zsh, and also any generic POSIX shell. z is only for zsh shells.
2. It is more feature-rich and very configurable. zoxide supports interactive queries/removes, configurable hooks, and more, while z seems more focused on being a barebones implementation.
3. The algorithm used is different, leading to better (in my opinion) results.
4. I created this because my prompt was slow, and z was being run upon every prompt. zoxide is much faster than any competitor that I've tested it against.

While compiling zoxide yourself does require Rust, one can simply use a pre-built binary from the Releases page. I've successfully used zoxide on Windows, macOS, and Linux.

zoxide is already being packaged for various OSes. The ones I'm aware of are Arch's AUR, Fedora COPR, nixpkgs, and a Homebrew tap (supporting macOS and Linux). I am not aware of how FreeBSD packaging works, but zoxide seems to be available on [FreshPorts](https://www.freshports.org/sysutils/zoxide/) too. I will update the README page soon, which will make installation easier for a number of users.

The installer is also written in POSIX shell - installation uses `sh`. It seems the shebang in the script uses bash for some reason - I will change that ASAP!

**Comment by herrbischoff** [comment]
Thanks for the info. The shell-independent argument is the strongest in my opinion. And since it's packaged for several platforms already, it's also easy to get. I would recommend adding the package managers to the install instructions, as you already plan to do. As soon as those are in place, I will gladly add `zoxide` to the list.

**Comment by ajeetdsouza** [comment]
@herrbischoff I've added installation instructions for various package managers. Do take a look!

**Comment by herrbischoff** [comment]
Thanks for the heads-up. LGTM, I'm going to merge this.

**Comment by ajeetdsouza** [comment]
Thanks!

**Pull request merged**
