### PR TITLE
Add stronghold

### PR DESCRIPTION
**Pull request by alichtman**

### CODE REVIEW

**Comment by herrbischoff** [comment]
While this is certainly interesting, I don't particularly like the Python dependency. As basically all this script does is running shell commands, it should have been coded in plain Bash, IMHO. I'll put this on the back burner and revisit it later.

**Comment by alichtman** [comment]
I coded this in Python because I was planning on adding a GUI, and that's a mess to do in Bash. I'm no longer planning on adding a GUI, but I understand why you may not want to add this to the list. Thanks for taking a look!

Edit: Could this belong in: https://github.com/herrbischoff/awesome-macos-command-line?

**Comment by herrbischoff** [comment]
Nah, same thing. I don't see why you should have to install Python and its tooling just to pretty up running a couple of shell commands. Same with the recent popularity of Node.js. I have a BSD background and like clean implementations. Yes, Bash is harder — but it's the included default shell in macOS and doesn't add any overhead.

Since the GUI idea is gone (which should always be clean and written in native Swift/Objective-C to be considered "awesome", BTW), if you rewrite it as a pure shell script at some point, I will gladly add it here. Same for your `shallow-backup` project.

**Comment by alichtman** [comment]
> which should always be clean and written in native Swift/Objective-C to be considered "awesome", BTW

You're definitely right about that.

I'll throw together a quick stronghold bash scrip sometime soon.

**Comment by alichtman** [comment]
Hey there, I just added a [bash script version of stronghold](https://github.com/alichtman/stronghold/blob/master/stronghold-script.sh).

It's not nearly as pretty, but has exactly the same functionality as the python version.

**Comment by herrbischoff** [comment]
You may want to check out this function to ask yes/no like you do in the Python version: https://gist.github.com/davejamesmiller/1965569

**Comment by alichtman** [comment]
Apparently, I have a lot to learn about bash scripting... Will incorporate this into the script.

**Pull request closed without merging**
