### PR TITLE
Add google drive upload to Cloud Services

### PR DESCRIPTION
**Pull request by labbots**
Added google-drive-upload utility to Cloud services. This cli tool allows users to upload files and folders to google drive from command line. It also has ability to upload files in parallel and resume interrupted uploads.

### CODE REVIEW

**Comment by labbots** [comment]
@herrbischoff any update on this PR?

**Comment by herrbischoff** [comment]
Thanks for the submission. After reviewing, I found that I will happily add it as soon as it moves away from is Linux-centric approach. For example, the service generation should either output generic instructions or add options for other OSs, like `launchd` for macOS, `rc` for several BSDs, `OpenRC` for several lightweight Linux distributions. The fact that it requires Bash reveals another Linuxism — you may as well require Python, Ruby or Node.js. Currently, Linux distributions are the only OSs that come with Bash installed. A quick flick through the commits also reveals that it originally used `#!/bin/bash`, yet another Linuxism. By any chance, do you use Linux? 😉

I will keep an eye on this but not include it as of yet.

**Comment by labbots** [comment]
@herrbischoff Thanks for your feedback. I will try incorporating service generation for other OS but at this point in time its difficult to port the script away from Bash but I will look into alternative approach.

**Comment by Akianonymus** [comment]
Well, posix approach isn't impossible, but gonna lose a feature i.e parallel uploading.

Otherwise, every part is possible to port, obviously at the cost of increased script resource usage and more dependency on external programs.

If parallel uploading is not much of a problem, then i guess it's worth porting to posix.

Also, rationally speaking, giving the year we are in, i.e 2020, bash isn't a luxury, but well we are talking about compatibility here, my bad. Well, rationally, such a complex program shouldn't be written in bash in the first place i guess. 

Edit: Probably found a way to port the parallel uploads part too, gotta dig a bit.

**Comment by herrbischoff** [comment]
Generally speaking, I favor solutions which utilize tools which are available on all Unix-y OSs by default, without using a package manager. This keeps everything lean, portable and future-proof. Example: when writing systems-level Python scripts, I almost never rely on external packages but instead exclusively leverage internal modules. This way, all you ever need to have installed is the interpreter. This argument does not hold for Bash, as it still relies on external tools. In contrast, every Unix-style OS contains at least one POSIX-compliant shell in its base install.

**Comment by Akianonymus** [comment]
@herrbischoff POSIX support has been added and is fully working for all it's a usescases.

Tested on ubuntu and macOS.

https://github.com/labbots/google-drive-upload

**Comment by herrbischoff** [comment]
Thanks for the ping, I'm going to take a look when I find the time, which should be shortly.

**Comment by herrbischoff** [comment]
Well, "shortly" turned into "quite a bit longer" but now I've merged it. Thanks again for the suggestion and bearing with me.

**Comment by labbots** [comment]
Thanks for merging. 👍

**Pull request merged**
