### PR TITLE
add terjira

### PR DESCRIPTION
**Pull request by keepcosmos**
It's a command line power tool for Jira

### CODE REVIEW

**Comment by herrbischoff** [comment]
Looks like a nice tool. However, please fix the entry according to the [Contribution Guidelines](https://github.com/herrbischoff/awesome-command-line-apps/blob/master/contributing.md), especially this point:

> Titles need to be capitalized properly. Don't be lazy. For help with this, see Online Capitalize Tool. Use Chicago Manual of Style rules.

**Comment by keepcosmos** [comment]
@herrbischoff Thanks, I updated

**Comment by herrbischoff** [comment]
I do not see any update yet.

**Comment by keepcosmos** [comment]
@herrbischoff  
I updated title(terjira -> Terjira) and add dot in end of line. 
I pushed with force after rebase. so u can't see any change. 
Should I need to fix more?

**Comment by herrbischoff** [comment]
Yes. As stated in https://github.com/herrbischoff/awesome-command-line-apps/pull/17#issuecomment-270810224, you did not follow the Contribution Guideline. Please double-check.

**Comment by keepcosmos** [comment]
@herrbischoff  Sorry, I can not catch any point of Guideline. Could you give me some help?

**Comment by herrbischoff** [comment]
https://headlinecapitalization.com/

**Comment by herrbischoff** [comment]
I'm just going to merge it and edit it later.

**Comment by keepcosmos** [comment]
Thanks!

**Pull request merged**
