### PR TITLE
Add Buku

### PR DESCRIPTION
**Pull request by jarun**
Buku is a powerful command-line bookmark manager. Features:

- Lightweight, clean interface
- Text editor integration
- Fetch page title, add tags and comments
- Multiple search modes (e.g. deep, regex)
- Continuous search at prompt, on the fly mode switch
- Open bookmarks and search results in browser
- Import/export in HTML (FF, Chrome compatible) or Markdown
- Shorten and expand URLs
- Smart tag editing with >>, > or << symbols at prompt
- Password protection (manual)
- Portable, merge-able database to sync between systems
- Multithreaded full DB refresh
- Shell completion scripts, man page with examples

### CODE REVIEW

**Comment by jarun** [comment]
Note: the build break isn't introduced by this PR.

**Comment by herrbischoff** [comment]
Looks interesting, like a local Pinboard clone. However, I don't quite see the appeal of managing bookmarks via the shell. It appears to be something that's done just for the heck of it, not offering true benefits of usability. Could you elaborate on why managing bookmarks this way is a good thing?

**Comment by jarun** [comment]
Privacy to begin with. Many people wouldn't want to share there personal bookmarks on a web portal.

Buku can integrate [well with the DE](https://github.com/jarun/Buku#gui-integration) and there are several other [projects](https://github.com/jarun/Buku#related-projects) (including a browser extension) which spawned from it.

**Comment by jarun** [comment]
But seriously, when one can quickly store a bookmark directly from the browser on a disk, refresh it anytime, search it in several powerful ways, optionally store the n-hash encrypted file on Dropbox/Box, open the bookmarks directly in the browser from a terminal (or just carry around in a pen-drive and use auto-merge on different systems...) why should one have to create an account on a third party website to share ones credentials... and bookmarks?

Your project says `awesome-command-line-apps` (which prompted me to share my utilities here) and then you exemplify `Pinboard`!!!

**Pull request closed without merging**
