### PR TITLE
Add awesome BOT tests

### PR DESCRIPTION
**Pull request by vinkla**
Added awesome bot tests. We need to enable Travis in order for this to work.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Cool, thank you!

**Comment by herrbischoff** [comment]
BTW: are you going to fix the links or should I? Making you a collaborator now.

**Comment by vinkla** [comment]
I can fix the links.

**Comment by vinkla** [comment]
All fixed :smile:

**Comment by herrbischoff** [comment]
Yay! :) Nice one. Thanks!

Also, if there are any useful shell applications you use, be sure to let me know.

**Comment by vinkla** [comment]
Sure, I'll whenever I find something good.

**Pull request merged**
