### PR TITLE
Add gtop

### PR DESCRIPTION
**Pull request by ihebu**
Added gtop, which is a system monitoring dashboard for terminal

### CODE REVIEW

**Comment by herrbischoff** [comment]
Do you think that Node.js (and by extension the almost completely un-audited NPM ecosystem) is the best scripting language to use to implement systems-level programming, even for monitoring purposes?

**Comment by ihebu** [comment]
As far as I know, npm packages are seeing  some noticeable security improvements since npm@6 with the audit feature and other measures, but I'm aware that security threats will always be present. After all I don't think it differs much from  python's PYPI or ruby's RubyGems packages etc, since they are un-audited as well.

If security is the main concern here, then yes It's probably better to choose another alternative to npm packages

**Comment by rottencandy** [comment]
Hi there, I don't have anything against `gtop`, but I think [`bottom`](https://github.com/ClementTsang/bottom) would be a much better alternative, both in terms of speed and memory footprint.

**Comment by ihebu** [comment]
@rottencandy  I agree ! bottom is much better :100:

**Comment by herrbischoff** [comment]
Thanks for the suggestion of bottom. Added via 9d2ff83.

**Pull request closed without merging**
