### PR TITLE
Add scrot

### PR DESCRIPTION
**Pull request by ihebu**
Added Scrot, which is a minimalist command line screen capturing application

### CODE REVIEW

**Comment by herrbischoff** [comment]
First off, a Wikipedia entry is not a valid link to software listed here. With a bit of sleuthing you'd have figured out that the most current repository is https://github.com/resurrecting-open-source-projects/scrot. A good reference is https://repology.org and then perusing the package sources of your favourite OS or distribution. I assume you're a Linux user.

Second, it requires X11 to run, which defeats the entire purpose of a command-line utility. We could just as well list any X11-compatible application here because they all have an executable that can be run *from* the shell but are useless *for* shell work.

To the best of my knowledge there is not a single application on this list that would require a GUI to run or be useful, with the exception of controlling a GUI application on macOS, where the Aqua WM is an integral part of the OS.

If you have a very good, thought out reason for why this particular application should be treated differently, I'd certainly like to hear it.

**Comment by ihebu** [comment]
Well I thought it was a really powerful yet simple tool. However, I get your point here. I guess I  misinterpreted the purpose of this repository.

Thank you for the valuable information

**Comment by xrat** [comment]
I wonder what command line tools are out there that are actually able to make screenshots. `scrot` *is* able to do it but I miss options for fine tuning.

**Comment by herrbischoff** [comment]
@IhebHaboubi Not a problem, you're welcome regardless. If you have other suggestions of great CLI tools with a TUI (as opposed to a GUI), don't hesitate to share.

**Comment by herrbischoff** [comment]
Regarding command line tools for screenshots, I don't see how this would work cleanly with a GUI of sorts. As terminal emulators are character-based, I suppose you'd have to implement something specific to an OS, like the frame buffer in Linux and somehow dump the current state of that to an image file.  But that's uninformed speculation.

If you do find something interesting regarding screenshots on the shell, let me know.

**Pull request closed without merging**
