### PR TITLE
Add googler

### PR DESCRIPTION
**Pull request by jarun**
googler is a power tool to Google (Web & News) and Google Site Search from the command-line.
Features:

- Google Search, Google Site Search, Google News
- Fast and clean (no ads, stray URLs or clutter), custom color
- Navigate result pages from omniprompt, open URLs in browser
- Effortless keyword-based site search with googler @t add-on
- Fetch n results in a go, start at the n<sup>th</sup> result
- Disable automatic spelling correction and search exact keywords
- Specify duration, country/domain (default: worldwide/.com), language
- Google keywords (e.g. `filetype:mime`, `site:somesite.com`) support
- Open the first result directly in browser (as in *I'm Feeling Lucky*)
- Non-stop searches: fire new searches at omniprompt without exiting
- HTTPS proxy, User Agent, TLS 1.2 (default) support
- Man page with examples, completion scripts for Bash, Zsh and Fish
- Minimal dependencies

### CODE REVIEW

**Comment by jarun** [comment]
Note: the build break isn't introduced by this PR.

**Comment by herrbischoff** [comment]
Looks quite useful, although I don't use Google any more. Merging.

**Comment by jarun** [comment]
> although I don't use Google any more

Is this project about "you"? I would suggest a private gist in that case.

**Comment by herrbischoff** [comment]
What exactly is your problem @jarun? It appears you need to adjust your attitude and not go around insulting people with differing viewpoints. Also, it seems you absolutely want to get things the wrong way and be confrontational about it. I suggest you calm down, take a deep breath and get your ego in check.

**Comment by jarun** [comment]
> although I don't use Google any more

all I am saying is, the above comment is irrelevant to merging this PR. Do you think it's relevant in anyway? Then please explain. I raised the PR because I assumed it will be useful for visitors to this public project.

**Comment by herrbischoff** [comment]
That is a comment, plain and simple. I review all submissions on the basis of their merits and potential benefits. The relevant part is

> Looks quite useful

just in case you were wondering. Also, merging your suggestion should have tipped you off to the fact that I see value in it beyond my own preferences. I don't feel I need to explain myself to you any further. Maybe after a good nights' sleep you can see that you are currently overreacting. Everybody hates a know-it-all, you know?

**Pull request merged**
