### PR TITLE
Add kakoune

### PR DESCRIPTION
**Pull request by Delapouite**
Hi

Kakoune is a text editor : http://kakoune.org

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for your suggestion. As I ask for in #20, could you elaborate on what sets this editor apart from Vim in a meaningful way? The website does not offer much in the way of motivation to use it.

**Comment by Delapouite** [comment]
Sure.
The philosophy of this editor and its strong points over vim are described in this overview by kakoune author : http://kakoune.org/why-kakoune/why-kakoune.html

**Comment by herrbischoff** [comment]
How about your personal opinion? Do you use it exclusively? What is exceptional for you?

**Comment by binhnguyen1512** [comment]
Hello ! Can you remote my phone 
This is comment in your my phone

**Review by herrbischoff — CHANGES_REQUESTED** [review]
I've decided to include the editor in the list. Please sort the entry correctly, remove the leading `A` from the description and I will merge.

**Comment by Delapouite** [comment]
I've updated this PR following your advices.

Thanks for your time.

**Review by herrbischoff — APPROVED** [review]

**Pull request merged**
